#!/bin/sh

export SCRIPTDIR=/home/andi/muggle/import
cd $SCRIPTDIR

echo "creating db"
mysql < createdb.mysql
 
echo "creating tables"
mysql < $SCRIPTDIR/createtables.mysql

echo "reading genres"
echo " use GiantDisc; load data local infile '$SCRIPTDIR/genres.txt' into table genre;"| mysql --local-infile=1 


echo "reading languages"
echo "use GiantDisc; load data local infile '$SCRIPTDIR/languages.txt' into table language;" | mysql --local-infile=1

echo "reading musictypes"
echo "use GiantDisc; load data local infile '$SCRIPTDIR/musictypes.txt' into table language;" | mysql --local-infile=1


echo "reading sources"
echo "use GiantDisc; load data local infile '$SCRIPTDIR/sources.txt' into table language;" | mysql --local-infile=1
