#!/bin/sh

export SCRIPTDIR=/home/lvw/Development/muggle-plugin/scripts
cd $SCRIPTDIR

echo "creating db"
mysql -u root < createdb.mysql
 
echo "creating tables"
mysql -u root < $SCRIPTDIR/createtables.mysql

echo "reading genres"
echo " use GiantDisc; load data local infile '$SCRIPTDIR/genres.txt' into table genre;"| mysql -u root --local-infile=1 

echo "reading languages"
echo "use GiantDisc; load data local infile '$SCRIPTDIR/languages.txt' into table language;" | mysql -u root --local-infile=1

echo "reading musictypes"
echo "use GiantDisc; load data local infile '$SCRIPTDIR/musictypes.txt' into table language;" | mysql -u root --local-infile=1

echo "reading sources"
echo "use GiantDisc; load data local infile '$SCRIPTDIR/sources.txt' into table language;" | mysql -u root --local-infile=1
